---
- name: Install Apache and upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: ./MyWebSite/ws.tar
    destin_file: /var/www/html
  
  tasks:
  - name: Install Apache Web Server
    yum: name=httpd state=latest
    
  - name: extract MyhomePage to Servers
    unarchive: src={{ source_file }} dest={{ destin_file }} mode=0555
  
  - name: Start WebServer and enable on boot
    service: name=httpd state=started enabled=yes
    notify: Restart Apache

  handlers:
   - name: Restart Apache
     service: name=httpd state=restarted
